package security

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/DangLong/na-server-go/pkg/utils"
)

// SetupSysctlHardening applies kernel-level network protections against DDoS and spoofing
func SetupSysctlHardening() {
	fmt.Println("\n   [*] Dang ap dung cac thong so bao ve he thong...")

	params := map[string]string{
		// === Chong SYN Flood ===
		"net.ipv4.tcp_syncookies":      "1",
		"net.ipv4.tcp_max_syn_backlog": "4096",
		"net.ipv4.tcp_synack_retries":  "2",
		"net.ipv4.tcp_syn_retries":     "3",

		// === Chong IP Spoofing ===
		"net.ipv4.conf.all.rp_filter":     "1",
		"net.ipv4.conf.default.rp_filter": "1",

		// === Tat cac tinh nang nguy hiem ===
		"net.ipv4.conf.all.accept_redirects":         "0",
		"net.ipv4.conf.default.accept_redirects":     "0",
		"net.ipv4.conf.all.send_redirects":           "0",
		"net.ipv4.conf.all.accept_source_route":      "0",
		"net.ipv4.icmp_echo_ignore_broadcasts":       "1",
		"net.ipv4.icmp_ignore_bogus_error_responses": "1",

		// === Tang hieu nang mang ===
		"net.core.somaxconn":            "65535",
		"net.core.netdev_max_backlog":   "4096",
		"net.ipv4.tcp_fin_timeout":      "15",
		"net.ipv4.tcp_tw_reuse":         "1",
		"net.ipv4.tcp_keepalive_time":   "300",
		"net.ipv4.tcp_keepalive_probes": "5",
		"net.ipv4.tcp_keepalive_intvl":  "15",
		"net.ipv4.ip_local_port_range":  "1024 65535",

		// === Log cac goi tin bi nghi ngo ===
		"net.ipv4.conf.all.log_martians":     "1",
		"net.ipv4.conf.default.log_martians": "1",
	}

	var lines []string
	lines = append(lines, "# === NALink Security Hardening ===")
	lines = append(lines, "# Auto-generated by NALink Server")
	lines = append(lines, "")

	for k, v := range params {
		lines = append(lines, fmt.Sprintf("%s = %s", k, v))
	}

	content := strings.Join(lines, "\n") + "\n"
	os.WriteFile("/etc/sysctl.d/99-nalink-security.conf", []byte(content), 0644)
	utils.ExecCmd("sysctl", "--system")

	fmt.Println("   \033[0;32m✔ Da ap dung bao ve he thong chong tan cong mang.\033[0m")
}

// SetupConnectionLimits uses iptables to limit connection rates (anti-DDoS)
func SetupConnectionLimits() {
	fmt.Println("\n   [*] Dang thiet lap gioi han ket noi chong DDoS...")

	rules := [][]string{
		// Gioi han so ket noi moi toi port 80/443 (30 ket noi / 60 giay / IP)
		{"-A", "INPUT", "-p", "tcp", "--dport", "80", "-m", "connlimit", "--connlimit-above", "30", "--connlimit-mask", "32", "-j", "DROP"},
		{"-A", "INPUT", "-p", "tcp", "--dport", "443", "-m", "connlimit", "--connlimit-above", "30", "--connlimit-mask", "32", "-j", "DROP"},

		// Rate limit SYN packets (chong SYN Flood nang)
		{"-A", "INPUT", "-p", "tcp", "--syn", "-m", "limit", "--limit", "25/s", "--limit-burst", "50", "-j", "ACCEPT"},
		{"-A", "INPUT", "-p", "tcp", "--syn", "-j", "DROP"},

		// Chong Ping Flood (gioi han ICMP)
		{"-A", "INPUT", "-p", "icmp", "--icmp-type", "echo-request", "-m", "limit", "--limit", "1/s", "--limit-burst", "4", "-j", "ACCEPT"},
		{"-A", "INPUT", "-p", "icmp", "--icmp-type", "echo-request", "-j", "DROP"},

		// Chong Port Scan (goi tin bat thuong)
		{"-A", "INPUT", "-p", "tcp", "--tcp-flags", "ALL", "NONE", "-j", "DROP"},
		{"-A", "INPUT", "-p", "tcp", "--tcp-flags", "ALL", "ALL", "-j", "DROP"},
		{"-A", "INPUT", "-p", "tcp", "--tcp-flags", "ALL", "FIN,URG,PSH", "-j", "DROP"},
		{"-A", "INPUT", "-p", "tcp", "--tcp-flags", "ALL", "SYN,RST,ACK,FIN,URG", "-j", "DROP"},
		{"-A", "INPUT", "-p", "tcp", "--tcp-flags", "SYN,RST", "SYN,RST", "-j", "DROP"},
		{"-A", "INPUT", "-p", "tcp", "--tcp-flags", "SYN,FIN", "SYN,FIN", "-j", "DROP"},
	}

	for _, rule := range rules {
		args := append([]string{"-C"}, rule[1:]...)
		// iptables -C tra ve loi (err != nil) neu rule CHUA ton tai.
		if _, err := utils.ExecCmd("iptables", args...); err != nil {
			utils.ExecCmd("iptables", rule...)
		}
	}

	// Luu lai de giữ khi reboot
	utils.ExecCmd("bash", "-c", "iptables-save > /etc/iptables.rules")

	// Tao service restore khi boot
	restoreService := `[Unit]
Description=Restore iptables rules
Before=network-pre.target
Wants=network-pre.target

[Service]
Type=oneshot
ExecStart=/sbin/iptables-restore /etc/iptables.rules
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
`
	os.WriteFile("/etc/systemd/system/iptables-restore.service", []byte(restoreService), 0644)
	utils.ExecCmd("systemctl", "daemon-reload")
	utils.ExecCmd("systemctl", "enable", "iptables-restore")

	fmt.Println("   \033[0;32m✔ Da thiet lap gioi han ket noi chong DDoS.\033[0m")
}

// SetupFail2BanAdvanced configures Fail2Ban for multiple services
func SetupFail2BanAdvanced(reader *bufio.Reader) {
	fmt.Println("\n   [*] Dang cau hinh bao mat nang cao...")

	// Doc SSH port hien tai
	sshConf := utils.ReadFileContent("/etc/ssh/sshd_config")
	sshPort := "22"
	for _, line := range strings.Split(sshConf, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "Port ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				sshPort = parts[1]
			}
		}
	}

	logPath := utils.GetLogPath()
	syslogPath := "/var/log/syslog"
	if !utils.IsDebian() {
		syslogPath = "/var/log/messages"
	}

	conf := fmt.Sprintf(`# === NALink Fail2Ban Configuration ===

[DEFAULT]
ignoreip = 127.0.0.1/8 ::1
bantime = 3600
findtime = 600
maxretry = 3
banaction = iptables-multiport

# === Chong Brute Force SSH ===
[sshd]
enabled = true
port = %s
filter = sshd
logpath = %s
maxretry = 3
bantime = 7200
findtime = 600

# === Chong Brute Force nhieu lan (ban lau hon) ===
[sshd-aggressive]
enabled = true
port = %s
filter = sshd
logpath = %s
maxretry = 5
bantime = 86400
findtime = 3600

# === Chong scan & tam do ket noi bat thuong ===
[recidive]
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
bantime = 604800
findtime = 86400
maxretry = 3

# === Chong HTTP Flood (neu dung Caddy/Nginx) ===
[http-get-dos]
enabled = true
port = http,https
filter = http-get-dos
logpath = %s
maxretry = 300
findtime = 300
bantime = 600
`, sshPort, logPath, sshPort, logPath, syslogPath)

	// Tao filter cho HTTP DoS
	httpFilter := `[Definition]
failregex = ^<HOST> -.*"(GET|POST).*
ignoreregex =
`
	os.MkdirAll("/etc/fail2ban/filter.d", 0755)
	os.WriteFile("/etc/fail2ban/filter.d/http-get-dos.conf", []byte(httpFilter), 0644)
	os.WriteFile("/etc/fail2ban/jail.local", []byte(conf), 0644)

	utils.ExecCmd("systemctl", "restart", "fail2ban")
	fmt.Println("   \033[0;32m✔ Bao mat nang cao da duoc cau hinh.\033[0m")
	fmt.Printf("   Port truy cap tu xa hien tai: %s\n", sshPort)
	fmt.Println("   - Chong brute-force: Chan 2h sau 3 lan sai | Chan 24h sau 5 lan sai")
	fmt.Println("   - Chong tai pham: Chan 7 ngay neu bi chan 3 lan")
	fmt.Println("   - Chong HTTP Flood: Chan 10 phut neu >300 request/5 phut")
}

// ShowFail2BanStatus displays current ban status
func ShowFail2BanStatus() {
	fmt.Println("\n\033[0;36m--- TRANG THAI BAO MAT ---\033[0m")
	out, _ := utils.ExecCmd("fail2ban-client", "status")
	fmt.Println(out)

	// Hien thi chi tiet cac jail
	for _, jail := range []string{"sshd", "sshd-aggressive", "recidive", "http-get-dos"} {
		jailOut, err := utils.ExecCmd("fail2ban-client", "status", jail)
		if err == nil && jailOut != "" {
			fmt.Printf("\n\033[1;33m[%s]\033[0m\n", strings.ToUpper(jail))
			fmt.Println(jailOut)
		}
	}
}

// ShowBlockedIPs shows currently banned IPs
func ShowBlockedIPs() {
	fmt.Println("\n\033[0;36m--- DANH SACH IP DANG BI CHAN ---\033[0m")
	out, _ := utils.ExecCmd("fail2ban-client", "banned")
	if strings.TrimSpace(out) == "" || strings.TrimSpace(out) == "[]" {
		fmt.Println("   (Khong co IP nao dang bi chan)")
	} else {
		fmt.Println(out)
	}

	fmt.Println("\n\033[0;36m--- DANH SACH IP BI CHAN DANG HOAT DONG ---\033[0m")
	iptOut, _ := utils.ExecCmd("iptables", "-L", "INPUT", "-n", "--line-numbers")
	for _, line := range strings.Split(iptOut, "\n") {
		if strings.Contains(line, "DROP") || strings.Contains(line, "REJECT") {
			fmt.Println("   " + line)
		}
	}
}

// UnbanIP removes an IP from Fail2Ban
func UnbanIP(reader *bufio.Reader) {
	fmt.Print("   Nhap IP can go chan: ")
	ip, _ := reader.ReadString('\n')
	ip = strings.TrimSpace(ip)
	if ip == "" {
		return
	}

	for _, jail := range []string{"sshd", "sshd-aggressive", "recidive", "http-get-dos"} {
		utils.ExecCmd("fail2ban-client", "set", jail, "unbanip", ip)
	}
	fmt.Printf("   \033[0;32m✔ Da go chan IP %s khoi he thong bao mat.\033[0m\n", ip)
}

// SecurityAudit runs a quick security check
func SecurityAudit(reader *bufio.Reader) {
	fmt.Println("\n\033[1;36m--- KIEM TRA BAO MAT HE THONG ---\033[0m\n")

	checks := []struct {
		name string
		cmd  string
		args []string
		good string
		bad  string
	}{
		{"Chong truy cap trai phep", "systemctl", []string{"is-active", "fail2ban"}, "active", "He thong bao mat dang chay"},
		{"Chong tan cong mang", "sysctl", []string{"-n", "net.ipv4.tcp_syncookies"}, "1", "Bao ve mang da bat"},
		{"Chong gia mao", "sysctl", []string{"-n", "net.ipv4.conf.all.rp_filter"}, "1", "Anti-spoofing da bat"},
		{"Chan broadcast", "sysctl", []string{"-n", "net.ipv4.icmp_echo_ignore_broadcasts"}, "1", "Chan broadcast"},
		{"Chan dinh tuyen gia", "sysctl", []string{"-n", "net.ipv4.conf.all.accept_source_route"}, "0", "Chan source routing"},
		{"Chan chuyen huong", "sysctl", []string{"-n", "net.ipv4.conf.all.accept_redirects"}, "0", "Chan redirect"},
		{"Ghi log bat thuong", "sysctl", []string{"-n", "net.ipv4.conf.all.log_martians"}, "1", "Log goi tin la"},
	}

	passed := 0
	total := len(checks)

	for _, c := range checks {
		out, _ := utils.ExecCmd(c.cmd, c.args...)
		out = strings.TrimSpace(out)
		if strings.Contains(out, c.good) {
			fmt.Printf("   \033[0;32m✔\033[0m %-25s \033[0;32mOK\033[0m\n", c.name)
			passed++
		} else {
			fmt.Printf("   \033[0;31m✘\033[0m %-25s \033[0;31mCHUA BAT\033[0m\n", c.name)
		}
	}

	// Kiem tra SSH
	sshConf := utils.ReadFileContent("/etc/ssh/sshd_config")
	sshChecks := map[string]string{
		"PermitRootLogin":      "no",
		"PermitEmptyPasswords": "no",
		"MaxAuthTries":         "3",
	}
	for k, v := range sshChecks {
		found := false
		for _, line := range strings.Split(sshConf, "\n") {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, k) && strings.Contains(line, v) {
				found = true
				break
			}
		}
		if found {
			fmt.Printf("   \033[0;32m✔\033[0m Bao mat %-15s \033[0;32mOK\033[0m\n", k)
			passed++
		} else {
			fmt.Printf("   \033[0;31m✘\033[0m Bao mat %-15s \033[0;31mCHUA THIET LAP\033[0m\n", k)
		}
		total++
	}

	fmt.Printf("\n   \033[1;36mKet qua: %d/%d kiem tra dat\033[0m\n", passed, total)
	if passed == total {
		fmt.Println("   \033[0;32m✔ He thong da duoc bao mat toi da!\033[0m")
		return
	}

	fmt.Println("   \033[1;33m[!] He thong chua dat yeu cau bao mat. Dang tu dong thiet lap...\033[0m")
	fmt.Println("\n   [*] Dang tu dong thiet lap cac chuc nang bao mat...")

	SetupSysctlHardening()
	SetupFail2BanAdvanced(reader)
	SetupConnectionLimits()

	fmt.Println("   - [90%] Dang thay doi port truy cap tu xa va cau hinh bao mat...")
	for k, v := range sshChecks {
		val := fmt.Sprintf("%s %s", k, v)
		checkCmd := fmt.Sprintf("grep -qE '^[#]*[[:space:]]*%s' /etc/ssh/sshd_config", k)
		if _, err := utils.ExecCmd("bash", "-c", checkCmd); err == nil {
			utils.ExecCmd("sed", "-i", "-E", fmt.Sprintf("s/^[#]*[[:space:]]*%s.*/%s/", k, val), "/etc/ssh/sshd_config")
		} else {
			f, _ := os.OpenFile("/etc/ssh/sshd_config", os.O_APPEND|os.O_WRONLY, 0644)
			if f != nil {
				f.WriteString(val + "\n")
				f.Close()
			}
		}
	}
	utils.ExecCmd("systemctl", "restart", "sshd")
	fmt.Println("   \033[0;32m✔ Da ap dung cau hinh truy cap tu xa an toan.\033[0m")

	fmt.Println("\n   \033[1;33m[!] Luu y: Tuong lua can phai thiet lap cung voi port truy cap nen he thong da bo qua.\033[0m")
	fmt.Println("   \033[1;33m    Neu Tuong lua chua bat, ban nen quay lai Menu Chinh -> Chuc nang 8 de cai dat dong bo.\033[0m")

	fmt.Println("\n   [*] Dang kiem tra lai he thong...")
	SecurityAudit(reader)
}
